name: Cypress Tests

on:
  pull_request:
    branches:
      - hard
    types:
      - synchronize
      - opened
      - reopened

  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Start server
        run: pnpm dev &
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:5173
      - name: Run Cypress tests
        run: pnpm run cypress:run
        env:
          CI: true
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/reports